version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: Akka.TestKit.Xunit2
    versions:
    - 1.4.16
    - 1.4.17
    - 1.4.18
  - dependency-name: Akka
    versions:
    - 1.4.16
    - 1.4.17
    - 1.4.18
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: MinVer
    versions:
    - 2.4.0
